name: CI

on: [push]

jobs:
  sast-scan:
    name: Bandit Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install Bandit
      run: pip install bandit
      
    - name: Run Bandit Scan
      run: bandit -ll -ii -r . -f json -o bandit_report.json

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: bandit-findings
        path: bandit_report.json

  
  image_scan:
    name: Build Image and Run Image Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pre-requisite to build Docker
      run: sudo apt-get update && apt-get install --no-install-recommends -y \
            dnsutils \
            libpq-dev=11.16-0+deb10u1 \
            python3-dev=3.7.3-1 && \
            apt-get clean && \
            rm -rf /var/lib/apt/lists/*

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      run: docker build -f Dockerfile -t myapp:latest .
        
    - name: Docker Scout Scan
      uses: docker/scout-action@v1.15.0
      with:
        dockerhub-user: ${{ secrets.DOCKER_USER }}
        dockerhub-password: ${{ secrets.DOCKER_PWD }}
        command: quickview,cves
        only-severities: critical,high
        sarif-file: scout-report.sarif
       
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
          name: docker-scout-findings
          path: scout-report.sarif
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: false
      env:
          DOCKER_CONFIG: /home/runner/.docker
          DOCKER_CLI_EXPERIMENTAL: enabled
